# Configuration file for AllosKin analysis
#
# Define the residues of interest here.
# The key (e.g., 'res_50_TM1') is a unique identifier.
# The value (e.g., 'resid 50') is an MDAnalysis selection string.
#
# These selections will be used by the FeatureExtractor.

# PIF
# residue_selections:
#   res_88: 'resid 88'
#   res_185: 'resid 185'
#   res_238: 'resid 238'
#   res_88_185: 'resid 88 185'
#   res_88_238: 'resid 88 238'
#   res_185_238: 'resid 185 238'
#   res_88_185_238: 'resid 88 185 238'

# NPxxY
# residue_selections:
#   res_280: 'resid 280'
#   res_281: 'resid 281'
#   res_282: 'resid 282'
#   res_283: 'resid 283'
#   res_284: 'resid 284'
#   res_285: 'resid 285'
#   res_280_281: 'resid 280 281'
#   res_280_282: 'resid 280 282'
#   res_280_283: 'resid 280 283'
#   res_280_284: 'resid 280 284'
#   res_280_285: 'resid 280 285'
#   res_281_282: 'resid 281 282'
#   res_281_283: 'resid 281 283'
#   res_281_284: 'resid 281 284'
#   res_281_285: 'resid 281 285'
#   res_282_283: 'resid 282 283'
#   res_282_284: 'resid 282 284'
#   res_282_285: 'resid 282 285'
#   res_283_284: 'resid 283 284'
#   res_283_285: 'resid 283 285'
#   res_284_285: 'resid 284 285'
#   res_280_281_282: 'resid 280 281 282'
#   res_280_281_283: 'resid 280 281 283'
#   res_280_281_284: 'resid 280 281 284'
#   res_280_281_285: 'resid 280 281 285'
#   res_280_282_283: 'resid 280 282 283'
#   res_280_282_284: 'resid 280 282 284'
#   res_280_282_285: 'resid 280 282 285'
#   res_280_283_284: 'resid 280 283 284'
#   res_280_283_285: 'resid 280 283 285'
#   res_280_284_285: 'resid 280 284 285'
#   res_281_282_283: 'resid 281 282 283'
#   res_281_282_284: 'resid 281 282 284'
#   res_281_282_285: 'resid 281 282 285'
#   res_281_283_284: 'resid 281 283 284'
#   res_281_283_285: 'resid 281 283 285'
#   res_281_284_285: 'resid 281 284 285'
#   res_282_283_284: 'resid 282 283 284'
#   res_282_283_285: 'resid 282 283 285'
#   res_282_284_285: 'resid 282 284 285'
#   res_283_284_285: 'resid 283 284 285'

# TM6-TM3 Ionic Lock
# residue_selections:
#   res_98: 'resid 98'
#   res_224: 'resid 224'
#   res_98_224: 'resid 98 224'

# Toggle Switch (PIF + TRP)
residue_selections:
  res_242: 'resid 242'
  res_242_88: 'resid 242 88'
  res_242_185: 'resid 242 185'
  res_242_238: 'resid 242 238'
  res_242_88_185: 'resid 242 88 185'
  res_242_88_238: 'resid 242 88 238'
  res_242_185_238: 'resid 242 185 238'
  res_242_88_185_238: 'resid 242 88 185 238'